### PR TITLE
Need to add 'lostFocus' emit event

### PR DESCRIPTION
**Pull request by durgeshahire4**
issue: #3

### CODE REVIEW

**Comment by durgeshahire4** [comment]
@miroshko Can you please review and merge this PR. So that we can use this ASAP. 
**also bump version**
Thanks in Advanced.

**Comment by miroshko** [comment]
I'm extending you PR with tests and then will bump the version and upload.

**Comment by miroshko** [comment]
closed due to 1423b2db8b5e39bc35b3b04a37b08c9c95f0dfde which repeats the change from this PR and has tests

**Comment by durgeshahire4** [comment]
@miroshko thanks

**Pull request closed without merging**
